app_platform_index:
    path:     /platform
    defaults: { _controller: PlatformBundle:Advert:index}

app_platform_sendmail:
    path:     /sendmail
    defaults: { _controller: PlatformBundle:Advert:mail}