app_platform_index:
    path:     /platform
    defaults: { _controller: PlatformBundle:Advert:index}

app_platform_sendmail:
    path:     /sendmail
    defaults: { _controller: PlatformBundle:Advert:mail}

app_blog:
    path:     /blog
    defaults: { _controller: PlatformBundle:Blog:blog}

app_query_list:
    path:     /query/list
    defaults: { _controller: PlatformBundle:Query:list}

