services:
#    platform.example:
#        class: PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    platform.antispam:
        class: PlatformBundle\Service\Antispam
        arguments: ["@mailer", "%locale%", "5"]

    platform.listener.article.logger:
        class: PlatformBundle\Listener\ArticleListener
        arguments:
            - "@monolog.logger.article"
        tags:
            - { name: doctrine.event_subscriber }

    platform.listener.category.logger:
        class: PlatformBundle\Listener\CategoryListener
        arguments:
            - "@monolog.logger.category"
        tags:
            - { name: doctrine.event_subscriber }

    platform.listener.tag.logger:
        class: PlatformBundle\Listener\TagListener
        arguments:
            - "@monolog.logger.tag"
        tags:
            - { name: doctrine.event_subscriber }

parameters:
    valeur_spam: 70