services:
#    platform.example:
#        class: PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    platform.antispam:
        class: PlatformBundle\Service\Antispam
        arguments: ["@mailer", "%locale%", "5"]

    platform.listener.article.logger:
        class: PlatformBundle\Listener\ArticleListener
        arguments:
            - "@logger"
        tags:
            - { name: monolog.logger, channel: "article" }

parameters:
    valeur_spam: 70