<?php

namespace PlatformBundle\Repository;

use PlatformBundle\Entity\Category;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findArticleByCategory(Category $category){
//        $qb = $this->createQueryBuilder('ac');
//
//        $qb->select('ac')
//            ->addSelect('b')
//            ->leftJoin('ac.category','c')
//            ->leftJoin('b.article','a')
//            ->where('a.category = :category')
//            ->setParameter('category', $category);
//
//        return $qb->getQuery()->getResult();
//    }
}
