<?php

namespace PlatformBundle\Repository;

use PlatformBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArticleByCategory($category){
        $qb = $this->createQueryBuilder('a');
            $qb->where('a.category = :category')
            ->setParameter('category', $category);


        return $qb->getQuery()->getResult();
    }
}
